package eav

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"unicode"

	"golang.org/x/text/unicode/norm"
)

var (
	machineNamePattern      = regexp.MustCompile(`^[a-z0-9_]+$`)
	errMachineNameEmpty     = errors.New("machine_name não pode ser vazio")
	errMachineNameFormat    = errors.New("use apenas letras minúsculas, números e underline no machine_name")
	errMachineNameTaken     = errors.New("já existe outro registro com este machine_name")
	errMachineNameExhausted = errors.New("não foi possível gerar um machine_name único")
)

func normalizeMachineNameCandidate(raw string) string {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return ""
	}

	lower := strings.ToLower(trimmed)
	normalized := norm.NFD.String(lower)

	var b strings.Builder
	lastUnderscore := false
	for _, r := range normalized {
		if unicode.Is(unicode.Mn, r) {
			continue
		}
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
			lastUnderscore = false
			continue
		}
		if r == '_' || r == '-' || unicode.IsSpace(r) {
			if b.Len() == 0 || lastUnderscore {
				continue
			}
			b.WriteByte('_')
			lastUnderscore = true
		}
	}

	candidate := strings.Trim(b.String(), "_")
	return candidate
}

func validateMachineName(candidate string) error {
	if candidate == "" {
		return errMachineNameEmpty
	}
	if !machineNamePattern.MatchString(candidate) {
		return errMachineNameFormat
	}
	return nil
}

func ensureMachineName(baseLabel, userInput string, exists func(string) (bool, error)) (string, bool, error) {
	machineName := normalizeMachineNameCandidate(userInput)
	autoGenerated := machineName == ""
	if autoGenerated {
		machineName = normalizeMachineNameCandidate(baseLabel)
	}

	err := validateMachineName(machineName)
	if err != nil {
		return "", autoGenerated, err
	}

	if !autoGenerated {
		var taken bool
		taken, err = exists(machineName)
		if err != nil {
			return "", autoGenerated, err
		}
		if taken {
			return "", autoGenerated, errMachineNameTaken
		}
		return machineName, autoGenerated, nil
	}

	candidate := machineName
	for i := 0; i < 5; i++ {
		var taken bool
		taken, err = exists(candidate)
		if err != nil {
			return "", autoGenerated, err
		}
		if !taken {
			return candidate, autoGenerated, nil
		}

		candidate, err = appendRandomSuffix(machineName)
		if err != nil {
			return "", autoGenerated, err
		}
	}

	return "", autoGenerated, errMachineNameExhausted
}

func isMachineNameUserError(err error) bool {
	if err == nil {
		return false
	}

	if errors.Is(err, errMachineNameEmpty) {
		return true
	}
	if errors.Is(err, errMachineNameFormat) {
		return true
	}
	if errors.Is(err, errMachineNameTaken) {
		return true
	}
	return errors.Is(err, errMachineNameExhausted)
}

func appendRandomSuffix(base string) (string, error) {
	suffix, err := randomHex(4)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%s_%s", base, suffix), nil
}

func randomHex(n int) (string, error) {
	buf := make([]byte, n/2)
	_, err := rand.Read(buf)
	if err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}
